sudo: false
branches:
  only:
    - master
    - /^v[0-9]/
language: node_js
node_js:
  - "node"
  - "lts/*"
cache:
  npm: true
install:
  - npm ci
script:
  - npm test
  - npm run build
deploy:
  - provider: npm
    skip_cleanup: true
    # TODO: Switch to a company owned account
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    # TODO: Change this to `latest` once I verify everything works
    tag: test
    on:
      tags: true
      # Only deploy from the LTS release
      node_js: "lts/*"
  - provider: pages
    skip_cleanup: true
    local_dir: docs
    # TODO: Switch to a company owned account
    github_token: $GITHUB_TOKEN
    on:
      tags: true
      # Only deploy from the LTS release
      node_js: "lts/*"
