# I believe this is now a default and can be safely removed
sudo: false
branches:
  only:
    # Only deploy "branches" (also tags) that are "master", or look like a
    # version tag. This way we can run tests against master, while also doing
    # `npm publish` when there's a new tag.
    - master
    - /^v[0-9]/
language: node_js
# Run tests against latest node and current long term support node. Only the LTS
# job is used for `npm publish`, since we don't want to publish the package
# twice (that would cause an error).
node_js:
  # - "node" // MRC-1258 - removed due to node 17 and/or Webpack issue
  # https://stackoverflow.com/questions/69665222/node-17-0-1-causes-some-error-digital-envelope-routinesunsupported
  - "lts/*"
# Cache npm downloads for faster CI jobs
cache:
  npm: true
before_install:
  # Decrypt Google Cloud Storage credentials
  - openssl aes-256-cbc -K $encrypted_9888058ce616_key -iv $encrypted_9888058ce616_iv -in gcs-key.json.enc -out gcs-key.json -d
# This might be the default these days, but I left it in explicitly
install:
  - npm ci
# "test" is actually ESLint + Prettier. Cypress tests are the only real tests in
# the repo right now.
script:
  - npm test
  - npm run build
  - npm run travis-cypress
deploy:
  # Copy the files in `gcs-files/` to Google Cloud Storage. This is used for
  # static assets, namely a lot of images.
  - provider: gcs
    # Opt-in to dpl v2 so we can use key_file
    # https://docs.travis-ci.com/user/deployment-v2/providers/gcs/
    edge: true
    key_file: gcs-key.json
    bucket: files.meridianapps.com
    skip_cleanup: true
    acl: public-read
    local_dir: gcs-files
    upload_dir: meridian-web-sdk
    on:
      node_js: "lts/*"
